live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 14
y = 10
